version: "2"

services:
  myweb:
      container_name: myweb
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./site.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - myphp
  myphp:
      container_name: myphp
      build: ./php/
      volumes:
          - ./web:/web
      links:
          - mydb

  mydb:
      container_name: mydb
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: dev
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: demo
