version: "3.7"
services:
  web:
    build: web
    image: somkiat/web:1.0
    ports:
      - 3000:3000
  db:
    build: database
    image: somkiat/db:1.0
    volumes:
      - pets-data:/var/lib/postgresql/data

volumes:
  pets-data: