version: '2'
services:
  web:
    container_name: web
    build: .
    ports:
      - 80:5000
    environment:
      - REDIS_HOST=redis

  redis:
    container_name: redis
    image: redis
    links:
      - web
