version: "3.8"

services: 
    api:
        build: ./api
        env_file:
            - ./config.env 
        ports: 
            - "3000:3000"
    db:
        build: ./db
        env_file:
            - ./config.env      
        volumes:
            - mysql_volume:/var/lib/mysql
        
volumes:
    mysql_volume:
    