#docker-compose up --scale web=3
version: '3.7'
services:
  web:
      image: web:1.0
      deploy:
        mode: replicated
        replicas: 5
  
  loadbalancer:
      image: load-balancer:1.0
      ports:
          - '8000:80'